<a href="https://colab.research.google.com/github/FranciniSantana/Data-Analysis-With-Python-FreeCodeCamp/blob/main/Projeto_Mean_Variance_Standard_Deviation_Calculator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Create a function named calculate() in mean_var_std.py that uses Numpy to output the mean, variance, standard deviation, max, min, and sum of the rows, columns, and elements in a 3 x 3 matrix.

The input of the function should be a list containing 9 digits. The function should convert the list into a 3 x 3 Numpy array, and then return a dictionary containing the mean, variance, standard deviation, max, min, and sum along both axes and for the flattened matrix.


In [1]:
import numpy as np
import pandas as pd


In [2]:
x = np.random.randint(100,size = (3,3))


In [3]:
x[[0,1,2]] # diferente de acessar uma lista por elemento, aqui eu aceso a linha inteira através do index.

array([[21, 79, 87],
       [89,  9, 27],
       [18, 10,  6]])

In [4]:
def calculate():
  x = np.array(x)


💡 Ler esse material: https://pythonexamples.org/numpy-mean/

In [10]:
len(list)

9

In [36]:
a = ([0,1,2,3,4,5,6,7,8])

In [22]:
arr = np.array(list)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
arrs = np.asarray(list)
arrs

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
list = [0,1,2,3,4,5,6,7,8] # variável contendo uma lista com 9 elementos

In [40]:
array = []  # para criar um array usei o método append para separar os elementos da lista em 3 listas

array.append(list[0:3])
array.append(list[3:6])
array.append(list[6:9])


array

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

In [41]:
np.array(array) # para transformar as três listas em um array usei o método np.array()

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])